# Generated by Django 5.1.4 on 2024-12-12 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings_api', '0002_alter_usermodel_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='meeting_count_of_users',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='meeting',
            name='meeting_duration_in_minutes',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='meeting',
            name='meeting_time',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_date',
            field=models.DateField(default='2021-01-01'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='password',
            field=models.CharField(max_length=1000),
        ),
    ]
