FROM nginx:alpine
#COPY index.html /usr/share/nginx/html/
#COPY auth.html /usr/share/nginx/html/
#COPY pages /usr/share/nginx/html/pages/
#COPY images /usr/share/nginx/html/images/
#COPY scripts /usr/share/nginx/html/scripts/
#COPY blocks /usr/share/nginx/html/blocks/
#COPY vendor /usr/share/nginx/html/vendor/

COPY . /usr/share/nginx/html/

EXPOSE 80
